### ISSUE TITLE
Lack of wiki page

### ISSUE THREAD

**Issue by heydba** [aliebelt/RibbonFX#1]
Hello. Sorry if I did posted it in the wrong place. I am new to both GitHub and JavaFX. Can you please post some kind of document explaining how to use this Ribbon component in an existing project?

**Comment by aliebelt** [comment]
Hello @ehimura, thanks for beeing interested in my RibbonFX component. Have a look into https://github.com/aliebelt/RibbonFX/blob/master/src/test/java/de/lit/ribbonfx/RibbonRunTest.java, there you can see how to use it. Currently I'm not happy with the API, but it's working. Also currently I think about moving the component to ControlsFX as a RibbonPane (with an updated API)...

**Comment by heydba** [comment]
Thankyou so much for that.

I certainly will watch that as an spectator (not a developer) cause I am
newbie into the JavaFX world.

Evandro Giachetto
Oracle DBA
evandrogiachetto@gmail.com

2015-07-12 7:28 GMT-03:00 Andreas Liebelt notifications@github.com:

**Comment by heydba** [comment]
I'm trying to run your code but it fails with the following error: Am I
missing anything?

I'm  using JDK 8u45.

Exception in Application start method
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
at
com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
at
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
at
com.sun.javafx.application.LauncherImpl$$Lambda$51/1642360923.run(Unknown
Source)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError:
com/airhacks/afterburner/views/FXMLView
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at de.lit.ribbonfx.SubSelector.<init>(SubSelector.java:21)
at
de.lit.ribbonfx.builder.SubSelectorBuilder.<init>(SubSelectorBuilder.java:29)
at
de.lit.ribbonfx.builder.SubSelectorBuilder.create(SubSelectorBuilder.java:36)
at javafxtestribbon.JavaFXTestRibbon.start(JavaFXTestRibbon.java:62)
at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
at com.sun.javafx.application.LauncherImpl$$Lambda$54/608295272.run(Unknown
Source)
at
com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
at com.sun.javafx.application.PlatformImpl$$Lambda$47/355629945.run(Unknown
Source)
at
com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
at com.sun.javafx.application.PlatformImpl$$Lambda$49/696728365.run(Unknown
Source)
at java.security.AccessController.doPrivileged(Native Method)
at
com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
at
com.sun.javafx.application.PlatformImpl$$Lambda$48/1915503092.run(Unknown
Source)
at
com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at
com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
at com.sun.glass.ui.win.WinApplication$$Lambda$37/1963387170.run(Unknown
Source)
... 1 more
Caused by: java.lang.ClassNotFoundException:
com.airhacks.afterburner.views.FXMLView
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 30 more
Exception running application javafxtestribbon.JavaFXTestRibbon
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Java Result: 1

The code:

/*
- To change this license header, choose License Headers in Project
  Properties.
- To change this template file, choose Tools | Templates
- and open the template in the editor.
  */
  package javafxtestribbon;

import de.lit.ribbonfx.Ribbon;
import de.lit.ribbonfx.SubSelector;
import de.lit.ribbonfx.actions.ButtonAction;
import de.lit.ribbonfx.builder.AppTabBuilder;
import de.lit.ribbonfx.builder.FooterBuilder;
import de.lit.ribbonfx.builder.GroupBuilder;
import de.lit.ribbonfx.builder.RibbonBuilder;
import de.lit.ribbonfx.builder.SimpleButtonBuilder;
import de.lit.ribbonfx.builder.SimpleFooterButtonBuilder;
import de.lit.ribbonfx.builder.SubSelectionBuilder;
import de.lit.ribbonfx.builder.SubSelectorBuilder;
import de.lit.ribbonfx.builder.SubSelectorButtonBuilder;
import de.lit.ribbonfx.builder.TabBuilder;
import de.lit.ribbonfx.model.AppTabData;
import de.lit.ribbonfx.model.CommonTabData;
import de.lit.ribbonfx.model.FooterData;
import de.lit.ribbonfx.model.GroupData;
import de.lit.ribbonfx.model.SimpleButtonData;
import de.lit.ribbonfx.model.SimpleFooterButtonData;
import de.lit.ribbonfx.model.SubSelectorButtonData;
import de.lit.ribbonfx.model.TabData;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
//import javafx.scene.control.Alert;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

/**
 *
- @author egiachetto
  */
  public class JavaFXTestRibbon extends Application {
  
  @Override
  public void start(Stage primaryStage) throws Exception {
      //Parent root =
  FXMLLoader.load(getClass().getResource("FXMLDocument.fxml"));
  
  ```
  //Scene scene = new Scene(root);
  
  //stage.setScene(scene);
  //stage.show();
  
  SubSelectorButtonData subSelectorTopButtonData1 =
  ```
  
  SubSelectorButtonBuilder.create().image(new
  Image("/images/save.png")).text("Speichern").build();
      CommonTabData subSelectionData1 =
  SubSelectionBuilder.create().title("Informationen").content(new Label("TODO
  1")).build();
      CommonTabData subSelectionData2 =
  SubSelectionBuilder.create().title("Zuletzt\nverwendet").content(new
  Label("TODO 2")).build();
      SubSelectorButtonData subSelectorBottomButtonData1 =
  SubSelectorButtonBuilder.create().text("Optionen").build();
      SubSelector appTabSubSelector =
  SubSelectorBuilder.create().accent(Color.RED).topButtons(subSelectorTopButtonData1)
              .subSelections(subSelectionData1,
  subSelectionData2).bottomButtons(subSelectorBottomButtonData1).build();
      AppTabData appTab =
  AppTabBuilder.create().title("Datei").content(appTabSubSelector).build();
      GroupData groupData11 =
  GroupBuilder.create().title("Zwischenablage").build();
      GroupData groupData12 =
  GroupBuilder.create().title("Schriftart").build();
      Label labelTab1 = new Label("Content of Tab 1");
      SimpleFooterButtonData simpleFooterButtonData1=
  SimpleFooterButtonBuilder.create().text("Seite: 1 von 1").build();
      SimpleFooterButtonData simpleFooterButtonData2 =
  SimpleFooterButtonBuilder.create().image(new
  Image("/images/no-macro-recording.png")).text("Macro").build();
  SimpleFooterButtonData simpleFooterButtonData3 =
  SimpleFooterButtonBuilder.create().image(new
  Image("/images/no-macro-recording.png")).build();
  FooterData footer =
  FooterBuilder.create().leftButtons(simpleFooterButtonData1,
  simpleFooterButtonData2).rightButtons(simpleFooterButtonData3).build();
  TabData tab1 = TabBuilder.create().title("Start").groups(groupData11,
  groupData12).content(labelTab1).footer(footer).build();
  GroupData groupData21 = GroupBuilder.create().title("Tabellen").build();
  GroupData groupData22 =
  GroupBuilder.create().title("Illustrationen").build();
  GroupData groupData23 = GroupBuilder.create().title("Diagramme").build();
  GroupData groupData24 = GroupBuilder.create().title("Sparklines").build();
  SimpleButtonData simpleButtonData251 =
  SimpleButtonBuilder.create().image(new
  Image("/images/data-cutting.png")).text("Datenschn.").build();
  GroupData groupData25 =
  GroupBuilder.create().title("Filter").buttons(simpleButtonData251).build();
  Label labelTab23 = new Label("Common content of Tab 2 and 3");
  TabData tab2 = TabBuilder.create().title("Einfügen").groups(groupData21,
  groupData22, groupData23, groupData24,
  groupData25).content(labelTab23).footer(footer).build();
  TabData tab3 =
  TabBuilder.create().title("Seitenlayout").content(labelTab23).footer(footer).build();
  Ribbon ribbon = RibbonBuilder.create().appTab(appTab).tabs(tab1, tab2,
  tab3).build();
  
  ```
  ribbon.setOnAction(new EventHandler<ActionEvent>() {
  ```
  
  @Override
  public void handle(ActionEvent event) {
  ButtonAction buttonAction = (ButtonAction) event;
  if (simpleButtonData251.equals(buttonAction.getButtonData())) {
                                  //Alert alert = new
  Alert(Alert.AlertType.INFORMATION);
                                  //alert.setTitle("Button Fired");
                                  //alert.setHeaderText("Button \"" +
  simpleButtonData251.text().get() + "\" fired...");
                                  //alert.setContentText("Conten text
  message button");
                                  System.out.println("Button \"" +
  simpleButtonData251.text().get() + "\" fired...");
  //Dialogs.create().title("ButtonAction").message("Button \"" +
  simpleButtonData251.text().get() + "\" fired...").showInformation();

}
}
});

```
    primaryStage.setScene(new Scene(ribbon, 650, 350,
```

Color.TRANSPARENT));
primaryStage.initStyle(StageStyle.UNIFIED);
primaryStage.show();
    }

```
/**
 * @param args the command line arguments
 */
public static void main(String[] args) {
    launch(args);
}
```

}

Evandro Giachetto
Oracle DBA
evandrogiachetto@gmail.com

2015-07-13 8:49 GMT-03:00 Evandro Giachetto evandrogiachetto@gmail.com:

**Comment by aliebelt** [comment]
Hi, you need following dependency to use RibbonFX:

```
<dependency>
    <groupId>com.airhacks</groupId>
    <artifactId>afterburner.fx</artifactId>
    <version>1.6.2</version>
</dependency>
```
